######################################################################
# Automatically generated by qmake (2.01a) pon. gru 15 22:30:47 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXX += -ggdb3
QMAKE_CXXFLAGS_THREAD = -O0

# Input
HEADERS += SobelApp.hh SobMainWin.hh
FORMS += sobel.ui
SOURCES += SMWImgOps.cc sobel.cc SobelApp.cc SobMainWin.cc
